# OCR

In [20]:
import os
import pandas as pd

# Define the directory containing the CSV files
csv_dir = r'assets/result/csv'

# List all CSV files in the directory
csv_files = [os.path.join(csv_dir, f) for f in os.listdir(csv_dir) if f.endswith('.csv')]

# Read and merge all CSV files
dataframes = [pd.read_csv(file) for file in csv_files]
merged_df = pd.concat(dataframes, ignore_index=True)
merged_df

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y
0,frame_000000.jpg,assets\frames\1,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,frame_000012.jpg,assets\frames\1,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,frame_000024.jpg,assets\frames\1,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,frame_000036.jpg,assets\frames\1,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,frame_000048.jpg,assets\frames\1,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36903,frame_033996.jpg,assets\frames\9,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36904,frame_034008.jpg,assets\frames\9,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36905,frame_034020.jpg,assets\frames\9,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36906,frame_034032.jpg,assets\frames\9,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36907,frame_034044.jpg,assets\frames\9,NaN,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
have_chat_data = merged_df[merged_df["have_sub"]]
have_chat_data

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y
63,frame_000756.jpg,assets\frames\1,小祥,0.999957,True,598.0,5.0,679.0,0.0,601.0,44.0,682.0,41.0
66,frame_000792.jpg,assets\frames\1,太好了,0.993245,True,481.0,6.0,596.0,6.0,481.0,44.0,596.0,44.0
67,frame_000804.jpg,assets\frames\1,太好了,0.992727,True,481.0,6.0,596.0,6.0,481.0,44.0,596.0,44.0
68,frame_000816.jpg,assets\frames\1,太好了,0.995613,True,480.0,6.0,596.0,6.0,480.0,44.0,596.0,44.0
70,frame_000840.jpg,assets\frames\1,怎麼濕成這樣,0.985218,True,448.0,9.0,677.0,5.0,448.0,44.0,677.0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36816,frame_032952.jpg,assets\frames\9,李廆玉博,0.727673,True,459.0,4.0,556.0,4.0,459.0,24.0,556.0,24.0
36817,frame_032964.jpg,assets\frames\9,李暠玉博,0.736070,True,459.0,4.0,556.0,4.0,459.0,24.0,556.0,24.0
36818,frame_032976.jpg,assets\frames\9,李廆玉博,0.732361,True,459.0,4.0,556.0,4.0,459.0,24.0,556.0,24.0
36819,frame_032988.jpg,assets\frames\9,李廆玉博,0.726971,True,459.0,4.0,556.0,4.0,459.0,24.0,556.0,24.0
36820,frame_033000.jpg,assets\frames\9,李暠玉博,0.738637,True,459.0,4.0,556.0,4.0,459.0,24.0,556.0,24.0

In [22]:
grouped = have_chat_data.groupby(['dir_name', 'image_name'])['speech'].nunique()
multiple_speech = grouped[grouped > 1]
count = multiple_speech.count()
count

0

In [23]:
grouped = have_chat_data.groupby('speech').size()
same_speech = grouped[grouped > 1]
count = same_speech.count()
count

2543

## Vanish the same speech

In [24]:
have_chat_data_sorted = have_chat_data.sort_values(by=['speech', 'score'], ascending=[True, False])
have_chat_data = have_chat_data_sorted.drop_duplicates(subset='speech', keep='first')
have_chat_data

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y
35070,frame_012000.jpg,assets\frames\9,!,0.588084,True,736.0,15.0,776.0,15.0,736.0,37.0,776.0,37.0
1116,frame_013392.jpg,assets\frames\1,/雨,0.746893,True,424.0,14.0,577.0,11.0,424.0,44.0,578.0,41.0
31799,frame_006732.jpg,assets\frames\8,0,0.787030,True,643.0,8.0,697.0,8.0,643.0,42.0,697.0,42.0
24509,frame_021420.jpg,assets\frames\5,000,0.722370,True,711.0,18.0,752.0,18.0,711.0,34.0,752.0,34.0
15660,frame_017400.jpg,assets\frames\2,0B,0.571974,True,488.0,8.0,561.0,8.0,488.0,39.0,561.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29760,frame_016320.jpg,assets\frames\7,：,0.669332,True,759.0,20.0,788.0,20.0,759.0,35.0,788.0,35.0
29223,frame_009876.jpg,assets\frames\7,：Ne,0.586199,True,900.0,14.0,1012.0,14.0,900.0,39.0,1012.0,39.0
1115,frame_013380.jpg,assets\frames\1,：休育館,0.796444,True,534.0,18.0,643.0,6.0,537.0,44.0,646.0,37.0
35887,frame_021804.jpg,assets\frames\9,］大家都不舒服呢,0.901069,True,657.0,11.0,944.0,8.0,658.0,44.0,944.0,42.0
15118,frame_010896.jpg,assets\frames\2,￥600,0.916261,True,610.0,8.0,672.0,0.0,614.0,39.0,676.0,30.0

In [25]:
have_chat_data.sort_values(by='score', ascending=False)

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y
29372,frame_011664.jpg,assets\frames\7,我知道,1.000000,True,583.0,8.0,695.0,8.0,583.0,44.0,695.0,44.0
12005,frame_007596.jpg,assets\frames\13,我想,1.000000,True,444.0,4.0,527.0,4.0,444.0,44.0,527.0,44.0
34232,frame_001944.jpg,assets\frames\9,是的,1.000000,True,603.0,3.0,681.0,3.0,603.0,44.0,681.0,44.0
34156,frame_001032.jpg,assets\frames\9,我的,1.000000,True,580.0,3.0,660.0,3.0,580.0,44.0,660.0,44.0
35048,frame_011736.jpg,assets\frames\9,不知道,1.000000,True,583.0,8.0,696.0,8.0,583.0,44.0,696.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26902,frame_016080.jpg,assets\frames\6,鳳,0.502184,True,580.0,10.0,615.0,10.0,580.0,38.0,615.0,38.0
18096,frame_012576.jpg,assets\frames\3,天為長,0.502062,True,604.0,14.0,819.0,14.0,604.0,38.0,819.0,38.0
26412,frame_010200.jpg,assets\frames\6,GA,0.501459,True,507.0,7.0,529.0,7.0,507.0,18.0,529.0,18.0
21287,frame_016812.jpg,assets\frames\4,傻訴年步,0.500909,True,360.0,13.0,468.0,13.0,360.0,38.0,468.0,38.0
1499,frame_017988.jpg,assets\frames\1,壓,0.500671,True,650.0,13.0,712.0,2.0,655.0,44.0,717.0,32.0

In [26]:
low_score_count = have_chat_data[have_chat_data['score'] < 0.6].shape[0]
low_score_count

265

In [27]:
have_chat_data = have_chat_data[have_chat_data['score'] > 0.6]
have_chat_data

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y
1116,frame_013392.jpg,assets\frames\1,/雨,0.746893,True,424.0,14.0,577.0,11.0,424.0,44.0,578.0,41.0
31799,frame_006732.jpg,assets\frames\8,0,0.787030,True,643.0,8.0,697.0,8.0,643.0,42.0,697.0,42.0
24509,frame_021420.jpg,assets\frames\5,000,0.722370,True,711.0,18.0,752.0,18.0,711.0,34.0,752.0,34.0
1366,frame_016392.jpg,assets\frames\1,0U做RNG,0.804928,True,556.0,3.0,724.0,3.0,556.0,42.0,724.0,42.0
27439,frame_022524.jpg,assets\frames\6,0呵,0.623214,True,774.0,14.0,825.0,6.0,778.0,42.0,829.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23342,frame_007416.jpg,assets\frames\5,（春日影》變了啊,0.911441,True,505.0,10.0,793.0,5.0,506.0,44.0,794.0,43.0
29760,frame_016320.jpg,assets\frames\7,：,0.669332,True,759.0,20.0,788.0,20.0,759.0,35.0,788.0,35.0
1115,frame_013380.jpg,assets\frames\1,：休育館,0.796444,True,534.0,18.0,643.0,6.0,537.0,44.0,646.0,37.0
35887,frame_021804.jpg,assets\frames\9,］大家都不舒服呢,0.901069,True,657.0,11.0,944.0,8.0,658.0,44.0,944.0,42.0
15118,frame_010896.jpg,assets\frames\2,￥600,0.916261,True,610.0,8.0,672.0,0.0,614.0,39.0,676.0,30.0

In [28]:
have_chat_data['frame_number'] = have_chat_data['image_name'].apply(lambda x: int(x.split('_')[1].split('.')[0]))
have_chat_data['dir_number'] = have_chat_data['dir_name'].apply(lambda x: int(x.split('\\')[-1]))

sorted_df = have_chat_data.sort_values(by=['dir_number', 'frame_number'])

sorted_df

C:\Users\AORUS\AppData\Local\Temp\ipykernel_29432\233217484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  have_chat_data['frame_number'] = have_chat_data['image_name'].apply(lambda x: int(x.split('_')[1].split('.')[0]))
C:\Users\AORUS\AppData\Local\Temp\ipykernel_29432\233217484.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  have_chat_data['dir_number'] = have_chat_data['dir_name'].apply(lambda x: int(x.split('\\')[-1]))

,image_name,dir_name,speech,score,have_sub,left_top_x,left_top_y,right_top_x,right_top_y,left_bottom_x,left_bottom_y,right_bottom_x,right_bottom_y,frame_number,dir_number
68,frame_000816.jpg,assets\frames\1,太好了,0.995613,True,480.0,6.0,596.0,6.0,480.0,44.0,596.0,44.0,816,1
70,frame_000840.jpg,assets\frames\1,怎麼濕成這樣,0.985218,True,448.0,9.0,677.0,5.0,448.0,44.0,677.0,43.0,840,1
76,frame_000912.jpg,assets\frames\1,你最近不來學校,0.995313,True,392.0,7.0,659.0,10.0,392.0,41.0,658.0,44.0,912,1
79,frame_000948.jpg,assets\frames\1,奶最近不來學校,0.953339,True,390.0,5.0,660.0,9.0,389.0,43.0,660.0,44.0,948,1
85,frame_001020.jpg,assets\frames\1,今天我來是有話要說,0.976497,True,472.0,7.0,809.0,3.0,472.0,44.0,809.0,42.0,1020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14172,frame_033600.jpg,assets\frames\13,校下山佳,0.818678,True,940.0,2.0,1062.0,0.0,940.0,31.0,1063.0,28.0,33600,13
14174,frame_033624.jpg,assets\frames\13,拉下由佳,0.721245,True,941.0,3.0,1061.0,1.0,942.0,28.0,1061.0,27.0,33624,13
14178,frame_033672.jpg,assets\frames\13,崧下由佳,0.791757,True,941.0,3.0,1061.0,1.0,942.0,28.0,1061.0,27.0,33672,13
14200,frame_033936.jpg,assets\frames\13,我麵,0.600693,True,575.0,20.0,673.0,20.0,575.0,44.0,673.0,44.0,33936,13
14205,frame_033996.jpg,assets\frames\13,混蛋老多,0.770650,True,571.0,15.0,704.0,18.0,570.0,44.0,704.0,44.0,33996,13

In [33]:
sorted_df.to_csv(r"assets/speech/cleaned_data.csv", encoding='utf-8', index=False)

# ASS

In [60]:
import os
import pandas as pd

# Define the directory containing the CSV files
csv_dir = r'assets/subtitle_result/csv'

# List all CSV files in the directory
csv_files = [os.path.join(csv_dir, f) for f in os.listdir(csv_dir) if f.endswith('.csv')]

# Read and merge all CSV files
dataframes = []

for file in csv_files:
    df = pd.read_csv(file)
    # Add a new column to track the source file
    df['eps'] = os.path.basename(file).split('.')[0]
    dataframes.append(df)

# Concatenate all DataFrames
merged_df = pd.concat(dataframes, ignore_index=True)

# Display the merged DataFrame
merged_df

        start_time  end_time         speech  start_frame  end_frame eps
0            31230     32000           祥ちゃん          748        767   1
1            31230     32000             小祥          748        767   1
2            32560     34250     良かった　来てくれて          780        821   1
3            32560     34250      太好了 妳終於來了          780        821   1
4            34650     36610  びしょぬれじゃない　大丈夫          830        877   1
...            ...       ...            ...          ...        ...  ..
285425     1397480   1405140              か        33506      33689   9
285426     1397530   1405210              ら        33507      33691   9
285427     1397530   1405210              ら        33507      33691   9
285428     1397530   1405210              ら        33507      33691   9
285429     1411100   1420070           一直迷茫        33832      34047   9

[285430 rows x 6 columns]

In [61]:
delete_speech = "m 20 0 b 10 0 0 10 0 20 b 0 31 10 40 20 40 b 31 40 40 31 40 20 b 40 10 31 0 20 0"

df_cleaned = merged_df[merged_df['speech'] != delete_speech]
df_cleaned

        start_time  end_time         speech  start_frame  end_frame eps
0            31230     32000           祥ちゃん          748        767   1
1            31230     32000             小祥          748        767   1
2            32560     34250     良かった　来てくれて          780        821   1
3            32560     34250      太好了 妳終於來了          780        821   1
4            34650     36610  びしょぬれじゃない　大丈夫          830        877   1
...            ...       ...            ...          ...        ...  ..
285425     1397480   1405140              か        33506      33689   9
285426     1397530   1405210              ら        33507      33691   9
285427     1397530   1405210              ら        33507      33691   9
285428     1397530   1405210              ら        33507      33691   9
285429     1411100   1420070           一直迷茫        33832      34047   9

[273748 rows x 6 columns]

In [62]:
from langdetect import detect, DetectorFactory

# Set the seed to ensure consistent results
DetectorFactory.seed = 0

# Define regular expressions to detect Chinese, Japanese, and English text
def detect_language(text: str) -> str:
    text = str(text)
    try:
        # Use langdetect to detect the language
        language = detect(text)
        
        # Map the detected language to your custom categories
        if language == 'zh-cn' or language == 'zh-tw':
            return "Chinese"
        elif language == 'ja':
            return "Japanese"
        elif language == 'en':
            return "English"
        else:
            return "Unknown"
    except Exception as e:
        # If an error occurs, return Unknown
        return "Unknown"

# Example: Applying this to your DataFrame
df_cleaned['language'] = df_cleaned['speech'].apply(detect_language)

df_cleaned

C:\Users\AORUS\AppData\Local\Temp\ipykernel_12604\2023511776.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['language'] = df_cleaned['speech'].apply(detect_language)

,start_time,end_time,speech,start_frame,end_frame,eps,language
0,31230,32000,祥ちゃん,748,767,1,Japanese
1,31230,32000,小祥,748,767,1,Unknown
2,32560,34250,良かった 来てくれて,780,821,1,Japanese
3,32560,34250,太好了 妳終於來了,780,821,1,Unknown
4,34650,36610,びしょぬれじゃない 大丈夫,830,877,1,Japanese
...,...,...,...,...,...,...,...
285425,1397480,1405140,か,33506,33689,9,Japanese
285426,1397530,1405210,ら,33507,33691,9,Japanese
285427,1397530,1405210,ら,33507,33691,9,Japanese
285428,1397530,1405210,ら,33507,33691,9,Japanese
285429,1411100,1420070,一直迷茫,33832,34047,9,Chinese

In [63]:
df_chinese = df_cleaned[df_cleaned['language'].isin(['Chinese', 'English', 'Unknown'])]
df_japanese = df_cleaned[df_cleaned['language'].isin(['Japanese', 'English', 'Unknown'])]

In [100]:
import pandas as pd

# 创建 DataFrame
df = df_japanese
result = []
temp_group = []  # 用于暂时存储相同 speech 的连续行

# 遍历 DataFrame
for i, row in df.iterrows():
    if not temp_group:
        temp_group.append(row)
    elif row["speech"] == temp_group[-1]["speech"]:  # 如果 speech 相同，继续合并
        temp_group.append(row)
    else:  # 如果 speech 不同，处理当前 group
        # 获取 min start_time 和 max end_time，合并成一行
        merged_row = {
            "speech": temp_group[0]["speech"],
            "start_time": min([r["start_time"] for r in temp_group]),
            "end_time": max([r["end_time"] for r in temp_group]),
            "start_frame": min([r["start_frame"] for r in temp_group]),  # 处理 start_frame
            "end_frame": max([r["end_frame"] for r in temp_group]),  # 处理 end_frame
            "eps": int(temp_group[0]["eps"])
        }
        result.append(merged_row)
        temp_group = [row]  # 重置为当前行继续合并

# 处理最后一个 group
if temp_group:
    merged_row = {
        "speech": temp_group[0]["speech"],
        "start_time": min([r["start_time"] for r in temp_group]),
        "end_time": max([r["end_time"] for r in temp_group]),
        "start_frame": min([r["start_frame"] for r in temp_group]),
        "end_frame": max([r["end_frame"] for r in temp_group]),
        "eps": int(temp_group[0]["eps"])
    }
    result.append(merged_row)

# 创建 DataFrame 保存最终结果
merged_df = pd.DataFrame(result)

In [101]:
merged_df = merged_df.sort_values(by=['eps','start_time'], ascending=[True,True])

In [102]:
merged_df = merged_df[merged_df['speech'].str.len() > 1]

merged_df

,speech,start_time,end_time,start_frame,end_frame,eps
0,祥ちゃん,31230,32000,748,767,1
1,小祥,31230,32000,748,767,1
2,良かった 来てくれて,32560,34250,780,821,1
3,太好了 妳終於來了,32560,34250,780,821,1
4,びしょぬれじゃない 大丈夫,34650,36610,830,877,1
...,...,...,...,...,...,...
7949,本字幕由喵萌Production製作 僅供交流試看之用 請勿用於商業用途\N翻譯：Ron...,1410100,1413100,33808,33880,13
7950,ただいま,1415100,1415970,33928,33949,13
7951,我回來了,1415100,1415970,33928,33949,13
7952,くそ親父,1417250,1418310,33980,34005,13
7953,混蛋老爸,1417250,1418310,33980,34005,13

In [103]:
def get_average_frame(row):
    # Get the average of start and end frame
    avg_frame = int((row['start_frame'] + row['end_frame']) / 2)
    avg_frame = (avg_frame // 12) * 12 + 12
    # Make the result a multiple of 12
    return f"frame_{avg_frame:06d}.jpg"# Rounds up to the nearest multiple of 12

def get_start_frame(frame):
    frame_path = (frame // 12) * 12 + 12
    return f"frame_{frame_path:06d}.jpg"

def get_end_frame(frame):
    frame_path = (frame // 12) * 12
    return f"frame_{frame_path:06d}.jpg"

# Apply the adjustment to the 'start_frame' and 'end_frame' columns
merged_df['get_frame'] = merged_df.apply(get_average_frame, axis=1)
merged_df['start_frame'] = merged_df['start_frame'].apply(get_start_frame)
merged_df['end_frame'] = merged_df['end_frame'].apply(get_end_frame)

# Save the result to an Excel file
merged_df.to_excel(r"assets\speech\ass_result_jp.xlsx", index=False)